control 'SV-271334' do
  title 'SQL Server must reveal detailed error messages only to documented and approved individuals or roles.'
  desc %q(If SQL Server provides too much information in error logs and administrative messages to the screen, this could lead to compromise. The structure and content of error messages need to be carefully considered by the organization and development team. The extent to which the information system is able to identify and handle error conditions is guided by organizational policy and operational requirements. 
 
Some default DBMS error messages can contain information that could aid an attacker in, among other things, identifying the database type, host address, or state of the database. Custom errors may contain sensitive customer information. 
 
It is important that detailed error messages be visible only to those who are authorized to view them; that general users receive only generalized acknowledgment that errors have occurred; and that these generalized messages appear only when relevant to the user's task. For example, a message along the lines of, "An error has occurred. Unable to save your changes. If this problem persists, please contact your help desk." would be relevant. A message such as "Warning: your transaction generated a large number of page splits" would likely not be relevant. "ABGQ is not a valid widget code." would be appropriate; but "The INSERT statement conflicted with the FOREIGN KEY constraint "WidgetTransactionFK". The conflict occurred in database "DB7", table "dbo.WidgetMaster", column 'WidgetCode'" would not, as it reveals too much about the database structure.)
  desc 'check', 'Error messages within applications, custom database code (stored procedures, triggers) must be enforced by guidelines and code review practices.  

SQL Server generates certain system events and user-defined events to the SQL Server error log. The SQL Server error log can be viewed using SQL Server Management Studio GUI. All users granted the security admin or sysadmin level of permission are able to view the logs. Review the users returned in the following script: 

USE master 
GO
SELECT Name 
FROM syslogins 
WHERE (sysadmin = 1 or securityadmin = 1) 
and hasaccess = 1; 

If any nonauthorized users have access to the SQL Server Error Log located at Program Files\\Microsoft SQL Server\\MSSQL.n\\MSSQL\\LOG, this is a finding. 

In addition, the SQL Server Error Log is also located at Program Files\\Microsoft SQL Server\\MSSQL.n\\MSSQL\\LOG\\. Review the permissions on this folder to ensure that only authorized users are listed.  

If any nonauthorized users have access to the SQL Server Error Log in SQL Server Management Studio or if documentation does not exist stating that full error messages must be returned, this is a finding.

Otherwise, verify if trace flag 3625 is enabled to mask certain system-level error information returned to nonadministrative users. 
 
Launch SQL Server Configuration Manager >> select SQL Server Services >> select the SQL Server >> right-click and select Properties >> select Startup Parameters tab >> verify -T3625 exists in the dialogue window.

OR

Run the query:
DBCC TRACESTATUS;

If TraceFlag 3625 does not return with Status = 1, and if documentation does not exist stating that full error messages must be returned, this is a finding.'
  desc 'fix', 'Configure audit logging, tracing, and/or custom code in the database or application to record detailed error messages generated by SQL Server for review by authorized personnel. 
 
If any nonauthorized users have access to the SQL Server Error Log in SQL Server Management Studio, use the REVOKE or DENY commands to remove them from the security admin or sysadmin roles.
 
If any nonauthorized users have access to the SQL Server Error Log located at Program Files\\Microsoft SQL Server\\MSSQL.n\\MSSQL\\LOG, remove their permissions. 
 
Consider enabling trace flag 3625 to mask certain system-level error information returned to nonadministrative users. 

Configure audit logging, tracing and/or custom code in the database or application to record detailed error messages generated by SQL Server, for review by authorized personnel. 
 
If any nonauthorized users have access to the SQL Server Error Log in SQL Server Management Studio, use the REVOKE or DENY commands to remove them from the security admin or sysadmin roles.  

If any nonauthorized users have access to the SQL Server Error Log located at Program Files\\Microsoft SQL Server\\MSSQL.n\\MSSQL\\LOG, remove their permissions. 
 
Enable trace flag 3625 to mask certain system-level error information returned to nonadministrative users. 
 
To launch SQL Server Configuration Manager, select SQL Server Services, select the SQL Server, then right-click and select "Properties". Select the "Startup Parameters" tab, enter "-T3625", and then click "Add". Click "OK", then restart SQL instance.'
  impact 0.5
  tag check_id: 'C-75377r1109029_chk'
  tag severity: 'medium'
  tag gid: 'V-271334'
  tag rid: 'SV-271334r1109125_rule'
  tag stig_id: 'SQLI-22-010100'
  tag gtitle: 'SRG-APP-000267-DB-000163'
  tag fix_id: 'F-75284r1109030_fix'
  tag 'documentable'
  tag cci: ['CCI-001314']
  tag nist: ['SI-11 b']
end
